-- Migration 219: Foundation defensive column hardening
-- Ensures all foundation tables have bilingual + audit columns
-- Required by: foundation-*.component.ts signal refactor

DO $$ BEGIN ALTER TABLE departments ADD COLUMN IF NOT EXISTS name_ar VARCHAR(255); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE departments ADD COLUMN IF NOT EXISTS description_ar TEXT; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE departments ADD COLUMN IF NOT EXISTS head_user_id VARCHAR(64); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE departments ADD COLUMN IF NOT EXISTS parent_department_id UUID; EXCEPTION WHEN OTHERS THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE locations ADD COLUMN IF NOT EXISTS name_ar VARCHAR(255); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE locations ADD COLUMN IF NOT EXISTS address_ar TEXT; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE locations ADD COLUMN IF NOT EXISTS city_ar VARCHAR(255); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE locations ADD COLUMN IF NOT EXISTS country_code VARCHAR(3); EXCEPTION WHEN OTHERS THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE business_units ADD COLUMN IF NOT EXISTS name_ar VARCHAR(255); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE business_units ADD COLUMN IF NOT EXISTS description_ar TEXT; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE business_units ADD COLUMN IF NOT EXISTS head_user_id VARCHAR(64); EXCEPTION WHEN OTHERS THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE roles ADD COLUMN IF NOT EXISTS name_ar VARCHAR(255); EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE roles ADD COLUMN IF NOT EXISTS description_ar TEXT; EXCEPTION WHEN OTHERS THEN NULL; END $$;

DO $$ BEGIN CREATE INDEX IF NOT EXISTS idx_departments_parent ON departments(parent_department_id) WHERE parent_department_id IS NOT NULL; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE INDEX IF NOT EXISTS idx_departments_head ON departments(head_user_id) WHERE head_user_id IS NOT NULL; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN CREATE INDEX IF NOT EXISTS idx_locations_country ON locations(country_code); EXCEPTION WHEN OTHERS THEN NULL; END $$;
