import type { ConfigDefinitionCreateInput } from './config.schemas';

export const SEED_CONFIG_DEFINITIONS: ConfigDefinitionCreateInput[] = [
  // ═══════════════════════════════════════════════
  // DEPLOYMENT — infrastructure-level, platform-only
  // ═══════════════════════════════════════════════
  {
    key: 'deployment.mode',
    label: 'Deployment Mode',
    ownerDomain: 'platform',
    category: 'deployment',
    valueType: 'enum',
    allowedScopes: ['deployment', 'platform'],
    enumValues: ['saas', 'onprem', 'sovereign', 'sdk'],
    defaultValue: 'saas',
    isSecret: false,
    isRequired: true,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: true,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'deployment.airgapped.enabled',
    label: 'Air-Gapped Mode',
    ownerDomain: 'platform',
    category: 'deployment',
    valueType: 'boolean',
    allowedScopes: ['deployment', 'platform'],
    defaultValue: false,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: true,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'deployment.secrets.provider',
    label: 'Secrets Provider',
    ownerDomain: 'platform',
    category: 'deployment',
    valueType: 'enum',
    allowedScopes: ['deployment', 'platform'],
    enumValues: ['env', 'cloud_kms', 'local_vault', 'hsm'],
    defaultValue: 'env',
    isSecret: false,
    isRequired: true,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: true,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'deployment.storage.objectStore',
    label: 'Object Storage Provider',
    ownerDomain: 'platform',
    category: 'deployment',
    valueType: 'enum',
    allowedScopes: ['deployment', 'platform'],
    enumValues: ['local', 's3', 'azure_blob', 'minio'],
    defaultValue: 'local',
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: true,
    sdkExposable: false,
    uiExposable: true,
  },

  // ═══════════════════════════════════════════════
  // PLATFORM — core platform behaviour
  // ═══════════════════════════════════════════════
  {
    key: 'platform.observability.telemetryEnabled',
    label: 'Telemetry Enabled',
    ownerDomain: 'platform',
    category: 'observability',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'platform.branding.primaryColor',
    label: 'Primary Brand Color',
    ownerDomain: 'platform',
    category: 'branding',
    valueType: 'string',
    allowedScopes: ['platform', 'tenant', 'organization'],
    defaultValue: '#1a56db',
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: false,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'platform.security.passwordPolicy',
    label: 'Password Policy',
    ownerDomain: 'platform',
    category: 'security',
    valueType: 'json',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: { minLength: 12, requireUppercase: true, requireNumber: true, requireSpecial: true },
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'platform.ui.enabled',
    label: 'UI Enabled',
    ownerDomain: 'platform',
    category: 'platform',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: true,
    sdkExposable: true,
    uiExposable: false,
  },
  {
    key: 'platform.api.publicMode',
    label: 'Public API Mode',
    ownerDomain: 'platform',
    category: 'platform',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: false,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: true,
    sdkExposable: true,
    uiExposable: false,
  },
  {
    key: 'platform.licensing.mode',
    label: 'Licensing Mode',
    ownerDomain: 'platform',
    category: 'licensing',
    valueType: 'enum',
    allowedScopes: ['deployment', 'platform'],
    enumValues: ['open', 'commercial', 'trial', 'enterprise'],
    defaultValue: 'open',
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: true,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'platform.logging.level',
    label: 'Log Level',
    ownerDomain: 'platform',
    category: 'observability',
    valueType: 'enum',
    allowedScopes: ['platform', 'tenant'],
    enumValues: ['debug', 'info', 'warn', 'error', 'fatal'],
    defaultValue: 'info',
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },

  // ═══════════════════════════════════════════════
  // AUTH — authentication & session management
  // ═══════════════════════════════════════════════
  {
    key: 'auth.session.maxAgeMinutes',
    label: 'Session Max Age (Minutes)',
    ownerDomain: 'auth',
    category: 'auth',
    valueType: 'number',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: 60,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'auth.mfa.required',
    label: 'MFA Required',
    ownerDomain: 'auth',
    category: 'auth',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant', 'organization'],
    defaultValue: false,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },

  // ═══════════════════════════════════════════════
  // AI — provider & model management
  // ═══════════════════════════════════════════════
  {
    key: 'ai.providers.default',
    label: 'Default AI Provider',
    ownerDomain: 'ai',
    category: 'ai',
    valueType: 'string',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: 'lmstudio',
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'ai.providers.allowed',
    label: 'Allowed AI Providers',
    ownerDomain: 'ai',
    category: 'ai',
    valueType: 'string_array',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: ['lmstudio', 'anthropic', 'azure', 'ollama'],
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'ai.llm.localOnly',
    label: 'Local-Only LLM Mode',
    ownerDomain: 'ai',
    category: 'ai',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: false,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'ai.agrc.enabled',
    label: 'AGRC AI Engine Enabled',
    ownerDomain: 'ai',
    category: 'ai',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },

  // ═══════════════════════════════════════════════
  // FEATURE FLAGS — platform infrastructure features
  // All previously in .env as *_ENABLED
  // ═══════════════════════════════════════════════
  {
    key: 'feature.temporal.enabled',
    label: 'Temporal Workflow Engine',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'feature.temporal.provisioning.enabled',
    label: 'Temporal Provisioning Workflows',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.openfga.enabled',
    label: 'OpenFGA Fine-Grained Authorization',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.bullmq.enabled',
    label: 'BullMQ Async Job Queue',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.pgmq.enabled',
    label: 'PostgreSQL Message Queue',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.age.enabled',
    label: 'Apache AGE Graph Extension',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.keyvault.enabled',
    label: 'Azure Key Vault Secrets Manager',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.asyncapi.validation.enabled',
    label: 'AsyncAPI Event Contract Validation',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.metrics.enabled',
    label: 'Prometheus Metrics',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.langfuse.enabled',
    label: 'Langfuse LLM Observability',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.langgraph.enabled',
    label: 'LangGraph Agent Orchestration',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'feature.langgraph.metrics.enabled',
    label: 'LangGraph Metrics Collection',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.clickhouse.enabled',
    label: 'ClickHouse Analytics',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.mcp.enabled',
    label: 'Model Context Protocol Server',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'feature.rls.enabled',
    label: 'Row-Level Security',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.otel.enabled',
    label: 'OpenTelemetry Tracing',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.pgvector.enabled',
    label: 'pgvector Vector Embeddings',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.unstructured.enabled',
    label: 'Unstructured Document Processing',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.openclaw.enabled',
    label: 'OpenClaw Legal Connector',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.openclaw.rateLimit.enabled',
    label: 'OpenClaw Rate Limiting',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.doganAiOs.enabled',
    label: 'Dogan-AI-OS Gateway',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.playwright.mcp.enabled',
    label: 'Playwright MCP Integration',
    ownerDomain: 'platform',
    category: 'feature',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: false,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },

  // ═══════════════════════════════════════════════
  // EXTERNAL SERVICES — third-party integrations
  // ═══════════════════════════════════════════════
  {
    key: 'feature.cisoAssistant.enabled',
    label: 'CISO Assistant Integration',
    ownerDomain: 'platform',
    category: 'external_service',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.openproject.enabled',
    label: 'OpenProject Integration',
    ownerDomain: 'platform',
    category: 'external_service',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'feature.govready.enabled',
    label: 'GovReady Integration',
    ownerDomain: 'platform',
    category: 'external_service',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },

  // ═══════════════════════════════════════════════
  // PRODUCT — product enablement (platform-neutral)
  // ═══════════════════════════════════════════════
  {
    key: 'product.default.enabled',
    label: 'Default Product Enabled',
    ownerDomain: 'product',
    category: 'product',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },

  // ═══════════════════════════════════════════════
  // MODULE — per-module configuration
  // ═══════════════════════════════════════════════
  {
    key: 'module.evidence.retentionDays',
    label: 'Evidence Retention (Days)',
    ownerDomain: 'module',
    category: 'module',
    valueType: 'number',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: 365,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'module.governance.enabled',
    label: 'Governance Module',
    ownerDomain: 'module',
    category: 'module',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'module.risk.enabled',
    label: 'Risk Module',
    ownerDomain: 'module',
    category: 'module',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'module.compliance.enabled',
    label: 'Compliance Module',
    ownerDomain: 'module',
    category: 'module',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'module.evidence.enabled',
    label: 'Evidence Module',
    ownerDomain: 'module',
    category: 'module',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'module.audit.enabled',
    label: 'Audit Module',
    ownerDomain: 'module',
    category: 'module',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'module.reporting.enabled',
    label: 'Reporting Module',
    ownerDomain: 'module',
    category: 'module',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },
  {
    key: 'module.ai.enabled',
    label: 'AI Module',
    ownerDomain: 'module',
    category: 'module',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: true,
    uiExposable: true,
  },

  // ═══════════════════════════════════════════════
  // TENANT — tenant-level configuration
  // ═══════════════════════════════════════════════
  {
    key: 'tenant.notifications.emailEnabled',
    label: 'Email Notifications Enabled',
    ownerDomain: 'tenant',
    category: 'notifications',
    valueType: 'boolean',
    allowedScopes: ['platform', 'tenant', 'organization', 'user'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'tenant.onboarding.mode',
    label: 'Onboarding Mode',
    ownerDomain: 'tenant',
    category: 'onboarding',
    valueType: 'enum',
    allowedScopes: ['platform', 'tenant'],
    enumValues: ['manual', 'guided', 'assisted', 'automated'],
    defaultValue: 'guided',
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'tenant.dashboard.defaultLayout',
    label: 'Default Dashboard Layout',
    ownerDomain: 'tenant',
    category: 'dashboard',
    valueType: 'enum',
    allowedScopes: ['platform', 'tenant', 'organization'],
    enumValues: ['executive', 'operational', 'compliance', 'risk', 'minimal'],
    defaultValue: 'executive',
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: false,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },

  // ═══════════════════════════════════════════════
  // USER — user-level preferences
  // ═══════════════════════════════════════════════
  {
    key: 'user.preferences.language',
    label: 'User Language Preference',
    ownerDomain: 'user',
    category: 'preferences',
    valueType: 'enum',
    allowedScopes: ['platform', 'tenant', 'organization', 'user'],
    enumValues: ['en', 'ar'],
    defaultValue: 'ar',
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: false,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'user.preferences.timezone',
    label: 'User Timezone Preference',
    ownerDomain: 'user',
    category: 'preferences',
    valueType: 'string',
    allowedScopes: ['platform', 'tenant', 'organization', 'user'],
    defaultValue: 'Asia/Riyadh',
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: false,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },

  // ═══════════════════════════════════════════════
  // PERFORMANCE — platform-level tuning
  // ═══════════════════════════════════════════════
  {
    key: 'platform.performance.dbPoolMax',
    label: 'Database Pool Max Connections',
    ownerDomain: 'platform',
    category: 'performance',
    valueType: 'number',
    allowedScopes: ['platform'],
    defaultValue: 20,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'platform.performance.compressionEnabled',
    label: 'HTTP Compression Enabled',
    ownerDomain: 'platform',
    category: 'performance',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'platform.performance.clusterEnabled',
    label: 'Cluster Mode Enabled',
    ownerDomain: 'platform',
    category: 'performance',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: true,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },

  // ═══════════════════════════════════════════════
  // SECURITY — rate limiting & headers
  // ═══════════════════════════════════════════════
  {
    key: 'platform.security.rateLimitEnabled',
    label: 'API Rate Limiting Enabled',
    ownerDomain: 'platform',
    category: 'security',
    valueType: 'boolean',
    allowedScopes: ['platform'],
    defaultValue: true,
    isSecret: false,
    isRequired: false,
    isOverridable: false,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
  {
    key: 'platform.security.apiMaxRequestsPerMinute',
    label: 'API Max Requests Per Minute',
    ownerDomain: 'platform',
    category: 'security',
    valueType: 'number',
    allowedScopes: ['platform', 'tenant'],
    defaultValue: 600,
    isSecret: false,
    isRequired: false,
    isOverridable: true,
    isLockable: true,
    requiresRestart: false,
    deploymentOnly: false,
    sdkExposable: false,
    uiExposable: true,
  },
];

export async function seedConfigDefinitions(
  repository: { findDefinitionByKey(key: string): Promise<unknown | null>; createDefinition(input: ConfigDefinitionCreateInput, actorUserId?: string): Promise<unknown> },
): Promise<{ seeded: number; skipped: number }> {
  let seeded = 0;
  let skipped = 0;
  for (const def of SEED_CONFIG_DEFINITIONS) {
    const existing = await repository.findDefinitionByKey(def.key);
    if (existing) {
      skipped++;
      continue;
    }
    await repository.createDefinition(def, undefined);
    seeded++;
  }
  return { seeded, skipped };
}
