// ============================================
// Platform — Auto-Task Routes
// 6 endpoints for auto-task configuration,
// task management, manual trigger, and stats.
// Internal auth (authenticate + tenantGuard).
//
// GET    /config
// PUT    /config
// GET    /tasks
// PUT    /tasks/:id
// POST   /trigger
// GET    /stats
//
// Requirements: 14.6, 21.1
// ============================================

import { Router, Request, Response } from 'express';
import { authenticate, requirePermission } from '../../../dauth';
import { tenantGuard } from '../guards/tenant-guard';
import { validate } from '../validation/validate';
import { auditMiddleware, setAuditData } from '../middleware/audit';
import { automationMiddleware } from '../middleware/automation';
import { autoTaskConfigBody, updateAutoTaskBody } from '../../../../modules/platform/schemas/platform.schemas';
import {
  getAutoTaskConfig,
  updateAutoTaskConfig,
  getAutoGeneratedTasks,
  updateAutoTask,
  triggerManualScan,
  getAutoTaskStats,
} from '../../../../modules/platform/services/auto/auto-task.service';
import { emitEvent } from '../../events/event-bus';
import { toErrorMessage } from '../../../../errors/http-error.util';
import { swallow, EC } from '../../resilience/resilient-catch';

const router = Router();

// All routes require internal auth + tenant guard
router.use(authenticate);
router.use(tenantGuard);
router.use(auditMiddleware('compliance'));
router.use(automationMiddleware('compliance'));

// GET /config — retrieve auto-task configuration
router.get('/config', requirePermission('workflow.task.read'), async (req: Request, res: Response) => {
  try {
    const config = await getAutoTaskConfig(req.tenantId!);
    res.json(config);
  } catch (err: unknown) {
    res.status(500).json({ error: toErrorMessage(err) || 'Failed to get auto-task config' });
  }
});

// PUT /config — update auto-task configuration
router.put(
  '/config',
  requirePermission('workflow.task.act'),
  validate({ body: autoTaskConfigBody }),
  async (req: Request, res: Response) => {
    try {
      const config = await updateAutoTaskConfig(req.tenantId!, req.body);
      setAuditData(res, { action: 'update', entityType: 'auto-task', entityId: req.tenantId!, afterState: config });
      swallow(
        EC.EVENT_BUS,
        emitEvent({ tenantId: req.tenantId!, userId: req.user!.userId, module: 'workflows', event: 'updated', entityType: 'auto_task', entityId: '' }),
        { tenantId: req.tenantId, operation: 'grcEvent:workflows.auto_task.updated' },
      );
      res.json(config);
    } catch (err: unknown) {
      res.status(500).json({ error: toErrorMessage(err) || 'Failed to update auto-task config' });
    }
  },
);

// GET /tasks — list auto-generated tasks
router.get('/tasks', requirePermission('workflow.task.read'), async (req: Request, res: Response) => {
  try {
    const filters = {
      status:     req.query.status     as string | undefined,
      entityType: req.query.entityType as string | undefined,
      limit:      req.query.limit  ? parseInt(req.query.limit  as string, 10) : undefined,
      offset:     req.query.offset ? parseInt(req.query.offset as string, 10) : undefined,
    };
    const tasks = await getAutoGeneratedTasks(req.tenantId!, filters);
    res.json(tasks);
  } catch (err: unknown) {
    res.status(500).json({ error: toErrorMessage(err) || 'Failed to get auto-generated tasks' });
  }
});

// PUT /tasks/:id — update an auto-generated task
router.put(
  '/tasks/:id',
  requirePermission('workflow.task.act'),
  validate({ body: updateAutoTaskBody }),
  async (req: Request, res: Response) => {
    try {
      const taskId = req.params.id as string;
      const task = await updateAutoTask(req.tenantId!, taskId, req.body);
      setAuditData(res, { action: 'update', entityType: 'auto-task', entityId: taskId, afterState: task });
      swallow(
        EC.EVENT_BUS,
        emitEvent({ tenantId: req.tenantId!, userId: req.user!.userId, module: 'workflows', event: 'updated', entityType: 'auto_task', entityId: taskId }),
        { tenantId: req.tenantId, operation: 'grcEvent:workflows.auto_task.updated' },
      );
      res.json(task);
    } catch (err: unknown) {
      const status = toErrorMessage(err) === 'Task not found' ? 404 : 500;
      res.status(status).json({ error: toErrorMessage(err) || 'Failed to update task' });
    }
  },
);

// POST /trigger — manually trigger auto-task scan
router.post('/trigger', requirePermission('workflow.task.act'), async (req: Request, res: Response) => {
  try {
    const result = await triggerManualScan(req.tenantId!);
    setAuditData(res, { action: 'create', entityType: 'auto-task', entityId: 'manual-trigger', afterState: result });
    swallow(
      EC.EVENT_BUS,
      emitEvent({ tenantId: req.tenantId!, userId: req.user!.userId, module: 'workflows', event: 'created', entityType: 'auto_task', entityId: 'manual-trigger' }),
      { tenantId: req.tenantId, operation: 'grcEvent:workflows.auto_task.created' },
    );
    res.json(result);
  } catch (err: unknown) {
    res.status(500).json({ error: toErrorMessage(err) || 'Failed to trigger auto-task scan' });
  }
});

// GET /stats — retrieve auto-task generation statistics
router.get('/stats', requirePermission('workflow.task.read'), async (req: Request, res: Response) => {
  try {
    const stats = await getAutoTaskStats(req.tenantId!);
    res.json(stats);
  } catch (err: unknown) {
    res.status(500).json({ error: toErrorMessage(err) || 'Failed to get auto-task stats' });
  }
});

export default router;
