/**
 * Contextual AI Types and Interfaces
 *
 * Shared type definitions for page-context-aware AI suggestions,
 * entity summaries, session persistence, and journey-aware extensions.
 *
 * Requirements: 4.1, 4.2, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 3.1, 3.2, 3.3
 */

// ============================================================================
// Core Types
// ============================================================================

/** Page context representing the user's current location and entity */
export interface PageContext {
  route: string;
  entityType?: string;
  entityId?: string;
  entityStatus?: string;
  module?: string;
  additionalData?: Record<string, any>;
}

/** AI suggestion with confidence scoring */
export interface AISuggestion {
  id: string;
  text: string;
  textAr: string;
  type: 'action' | 'insight' | 'warning' | 'recommendation';
  confidence: number;
  reasoning: string;
  entityType?: string;
  entityId?: string;
}

/** AI session for conversation context persistence */
export interface AISession {
  sessionId: string;
  userId: string;
  context: PageContext;
  messages: AIMessage[];
  createdAt: string;
  updatedAt: string;
}

/** AI conversation message */
export interface AIMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

/** Entity summary generated by AI */
export interface EntitySummary {
  entityType: string;
  entityId: string;
  summary: string;
  summaryAr: string;
  keyPoints: string[];
  riskLevel?: string;
  generatedAt: string;
}

// ============================================================================
// Journey-Aware Types (Task 10.1)
// ============================================================================

/** Module intro content with bilingual text */
export interface ModuleIntro {
  module: string;
  titleEn: string;
  titleAr: string;
  explanationEn: string;
  explanationAr: string;
  relevanceEn: string;
  relevanceAr: string;
}

/** Content suggestion for risk/policy/control creation */
export interface ContentSuggestion {
  id: string;
  entityType: 'risk' | 'policy' | 'control';
  titleEn: string;
  titleAr: string;
  bodyEn: string;
  bodyAr: string;
  frameworkRef?: string;
  confidence: number;
}

/** Journey-aware suggestion combining context + roadmap */
export interface JourneyAwareSuggestion {
  suggestions: AISuggestion[];
  nextActions: WhatNextAction[];
  moduleIntro?: ModuleIntro;
}

/** "What should I do next?" action item */
export interface WhatNextAction {
  taskId: string;
  titleEn: string;
  titleAr: string;
  descriptionEn: string;
  descriptionAr: string;
  targetModule: string;
  targetAction: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  reasonEn: string;
  reasonAr: string;
}
