/**
 * Command Registry
 *
 * All available commands organized by category.
 * Each command includes bilingual labels (English and Arabic) and permission requirements.
 *
 * Requirements: 6.2 - Command palette shows available commands based on user permissions
 */

import { Command } from './command-palette.types';

/**
 * COMMAND_REGISTRY contains all available commands organized by category.
 */
export const COMMAND_REGISTRY: Command[] = [
  // -------------------------------------------------------------------------
  // Navigation Commands - Navigate to different pages
  // -------------------------------------------------------------------------
  {
    id: 'nav-dashboard',
    label: 'Go to Dashboard',
    labelAr: 'الذهاب إلى لوحة التحكم',
    category: 'navigation',
    action: 'navigate',
    url: '/workspace-home',
    icon: 'pi pi-home',
    requiredPermission: 'workspace.config.read',
    shortcut: 'G D',
  },
  {
    id: 'nav-risks',
    label: 'Go to Risks',
    labelAr: 'الذهاب إلى المخاطر',
    category: 'navigation',
    action: 'navigate',
    url: '/risks',
    icon: 'pi pi-exclamation-triangle',
    requiredPermission: 'risk.record.read',
    shortcut: 'G R',
  },
  {
    id: 'nav-controls',
    label: 'Go to Controls',
    labelAr: 'الذهاب إلى الضوابط',
    category: 'navigation',
    action: 'navigate',
    url: '/controls',
    icon: 'pi pi-shield',
    requiredPermission: 'control.record.read',
    shortcut: 'G C',
  },
  {
    id: 'nav-policies',
    label: 'Go to Policies',
    labelAr: 'الذهاب إلى السياسات',
    category: 'navigation',
    action: 'navigate',
    url: '/policies',
    icon: 'pi pi-file',
    requiredPermission: 'policy.document.read',
    shortcut: 'G P',
  },
  {
    id: 'nav-frameworks',
    label: 'Go to Frameworks',
    labelAr: 'الذهاب إلى الأطر',
    category: 'navigation',
    action: 'navigate',
    url: '/frameworks',
    icon: 'pi pi-sitemap',
    requiredPermission: 'framework.record.read',
    shortcut: 'G F',
  },
  {
    id: 'nav-incidents',
    label: 'Go to Incidents',
    labelAr: 'الذهاب إلى الحوادث',
    category: 'navigation',
    action: 'navigate',
    url: '/incidents',
    icon: 'pi pi-bolt',
    requiredPermission: 'risk.record.read',
  },
  {
    id: 'nav-vendors',
    label: 'Go to Vendors',
    labelAr: 'الذهاب إلى الموردين',
    category: 'navigation',
    action: 'navigate',
    url: '/vendors',
    icon: 'pi pi-building',
    requiredPermission: 'risk.record.read',
  },
  {
    id: 'nav-evidence',
    label: 'Go to Evidence',
    labelAr: 'الذهاب إلى الأدلة',
    category: 'navigation',
    action: 'navigate',
    url: '/evidence',
    icon: 'pi pi-folder',
    requiredPermission: 'framework.record.read',
  },
  {
    id: 'nav-compliance',
    label: 'Go to Compliance',
    labelAr: 'الذهاب إلى الامتثال',
    category: 'navigation',
    action: 'navigate',
    url: '/compliance',
    icon: 'pi pi-check-circle',
    requiredPermission: 'framework.record.read',
  },
  {
    id: 'nav-audit',
    label: 'Go to Audit',
    labelAr: 'الذهاب إلى التدقيق',
    category: 'navigation',
    action: 'navigate',
    url: '/audit',
    icon: 'pi pi-search',
    requiredPermission: 'audit.record.read',
  },
  {
    id: 'nav-governance',
    label: 'Go to Governance',
    labelAr: 'الذهاب إلى الحوكمة',
    category: 'navigation',
    action: 'navigate',
    url: '/governance',
    icon: 'pi pi-briefcase',
    requiredPermission: 'policy.document.read',
  },
  {
    id: 'nav-workflows',
    label: 'Go to Workflows',
    labelAr: 'الذهاب إلى سير العمل',
    category: 'navigation',
    action: 'navigate',
    url: '/workflows',
    icon: 'pi pi-share-alt',
    requiredPermission: 'policy.document.read',
  },
  {
    id: 'nav-reports',
    label: 'Go to Reports',
    labelAr: 'الذهاب إلى التقارير',
    category: 'navigation',
    action: 'navigate',
    url: '/report-center',
    icon: 'pi pi-chart-bar',
    requiredPermission: 'report.document.read',
  },
  {
    id: 'nav-ai-hub',
    label: 'Go to AI Hub',
    labelAr: 'الذهاب إلى مركز الذكاء الاصطناعي',
    category: 'navigation',
    action: 'navigate',
    url: '/ai-hub',
    icon: 'pi pi-sparkles',
    requiredPermission: 'copilot.assistant.read',
  },
  {
    id: 'nav-registry',
    label: 'Go to Registry',
    labelAr: 'الذهاب إلى السجل',
    category: 'navigation',
    action: 'navigate',
    url: '/registry',
    icon: 'pi pi-database',
    requiredPermission: 'framework.record.read',
  },

  // -------------------------------------------------------------------------
  // Action Commands - Create new entities
  // -------------------------------------------------------------------------
  {
    id: 'action-create-risk',
    label: 'Create Risk',
    labelAr: 'إنشاء خطر',
    category: 'action',
    action: 'create',
    url: '/risks?action=create',
    icon: 'pi pi-plus',
    requiredPermission: 'risk.record.write',
    shortcut: 'C R',
  },
  {
    id: 'action-create-control',
    label: 'Create Control',
    labelAr: 'إنشاء ضابط',
    category: 'action',
    action: 'create',
    url: '/controls?action=create',
    icon: 'pi pi-plus',
    requiredPermission: 'control.record.write',
    shortcut: 'C C',
  },
  {
    id: 'action-create-policy',
    label: 'Create Policy',
    labelAr: 'إنشاء سياسة',
    category: 'action',
    action: 'create',
    url: '/policies?action=create',
    icon: 'pi pi-plus',
    requiredPermission: 'policy.document.write',
    shortcut: 'C P',
  },
  {
    id: 'action-create-incident',
    label: 'Create Incident',
    labelAr: 'إنشاء حادث',
    category: 'action',
    action: 'create',
    url: '/incidents?action=create',
    icon: 'pi pi-plus',
    requiredPermission: 'risk.record.write',
  },
  {
    id: 'action-create-vendor',
    label: 'Create Vendor',
    labelAr: 'إنشاء مورد',
    category: 'action',
    action: 'create',
    url: '/vendors?action=create',
    icon: 'pi pi-plus',
    requiredPermission: 'risk.record.write',
  },
  {
    id: 'action-create-evidence',
    label: 'Upload Evidence',
    labelAr: 'رفع دليل',
    category: 'action',
    action: 'create',
    url: '/evidence?action=upload',
    icon: 'pi pi-upload',
    requiredPermission: 'framework.record.write',
  },
  {
    id: 'action-create-workflow',
    label: 'Create Workflow',
    labelAr: 'إنشاء سير عمل',
    category: 'action',
    action: 'create',
    url: '/workflows?action=create',
    icon: 'pi pi-plus',
    requiredPermission: 'workflow.instance.write',
  },
  {
    id: 'action-create-assessment',
    label: 'Start Assessment',
    labelAr: 'بدء التقييم',
    category: 'action',
    action: 'create',
    url: '/maturity?action=start',
    icon: 'pi pi-play',
    requiredPermission: 'assessment.record.write',
  },

  // -------------------------------------------------------------------------
  // Search Commands - Search across entities
  // -------------------------------------------------------------------------
  {
    id: 'search-global',
    label: 'Global Search',
    labelAr: 'البحث الشامل',
    category: 'search',
    action: 'search',
    url: '/global-search',
    icon: 'pi pi-search',
    requiredPermission: 'workspace.config.read',
    shortcut: '/',
  },
  {
    id: 'search-risks',
    label: 'Search Risks',
    labelAr: 'البحث في المخاطر',
    category: 'search',
    action: 'search',
    url: '/global-search?type=risk',
    icon: 'pi pi-search',
    requiredPermission: 'risk.record.read',
  },
  {
    id: 'search-controls',
    label: 'Search Controls',
    labelAr: 'البحث في الضوابط',
    category: 'search',
    action: 'search',
    url: '/global-search?type=control',
    icon: 'pi pi-search',
    requiredPermission: 'control.record.read',
  },
  {
    id: 'search-policies',
    label: 'Search Policies',
    labelAr: 'البحث في السياسات',
    category: 'search',
    action: 'search',
    url: '/global-search?type=policy',
    icon: 'pi pi-search',
    requiredPermission: 'policy.document.read',
  },
  {
    id: 'search-frameworks',
    label: 'Search Frameworks',
    labelAr: 'البحث في الأطر',
    category: 'search',
    action: 'search',
    url: '/global-search?type=framework',
    icon: 'pi pi-search',
    requiredPermission: 'framework.record.read',
  },
  {
    id: 'search-evidence',
    label: 'Search Evidence',
    labelAr: 'البحث في الأدلة',
    category: 'search',
    action: 'search',
    url: '/global-search?type=evidence',
    icon: 'pi pi-search',
    requiredPermission: 'framework.record.read',
  },

  // -------------------------------------------------------------------------
  // Settings Commands - User preferences and settings
  // -------------------------------------------------------------------------
  {
    id: 'settings-profile',
    label: 'My Profile',
    labelAr: 'ملفي الشخصي',
    category: 'settings',
    action: 'navigate',
    url: '/profile',
    icon: 'pi pi-user',
    requiredPermission: 'workspace.config.read',
  },
  {
    id: 'settings-notifications',
    label: 'Notification Settings',
    labelAr: 'إعدادات الإشعارات',
    category: 'settings',
    action: 'navigate',
    url: '/notifications',
    icon: 'pi pi-bell',
    requiredPermission: 'workspace.config.read',
  },
  {
    id: 'settings-team',
    label: 'Team Management',
    labelAr: 'إدارة الفريق',
    category: 'settings',
    action: 'navigate',
    url: '/team-management',
    icon: 'pi pi-users',
    requiredPermission: 'workspace.config.read',
  },
  {
    id: 'settings-admin',
    label: 'Admin Dashboard',
    labelAr: 'لوحة تحكم المسؤول',
    category: 'settings',
    action: 'navigate',
    url: '/admin',
    icon: 'pi pi-cog',
    requiredPermission: 'admin.system.read',
  },
  {
    id: 'settings-tenant',
    label: 'Tenant Configuration',
    labelAr: 'إعدادات المستأجر',
    category: 'settings',
    action: 'navigate',
    url: '/tenant-config',
    icon: 'pi pi-sliders-h',
    requiredPermission: 'admin.system.write',
  },
  {
    id: 'settings-integrations',
    label: 'Integrations',
    labelAr: 'التكاملات',
    category: 'settings',
    action: 'navigate',
    url: '/integrations',
    icon: 'pi pi-link',
    requiredPermission: 'integrations.connector.read',
  },

  // -------------------------------------------------------------------------
  // Workspace Commands - Workspace management
  // -------------------------------------------------------------------------
  {
    id: 'workspace-switch',
    label: 'Switch Workspace',
    labelAr: 'تبديل مساحة العمل',
    category: 'workspace',
    action: 'workspace-switch',
    icon: 'pi pi-sync',
    requiredPermission: 'workspace.config.read',
  },
  {
    id: 'workspace-activity',
    label: 'Activity Feed',
    labelAr: 'سجل النشاط',
    category: 'workspace',
    action: 'navigate',
    url: '/activity-feed',
    icon: 'pi pi-history',
    requiredPermission: 'workspace.config.read',
  },
  {
    id: 'workspace-playbook',
    label: 'Playbook',
    labelAr: 'دليل العمل',
    category: 'workspace',
    action: 'navigate',
    url: '/playbook',
    icon: 'pi pi-book',
    requiredPermission: 'workspace.config.read',
  },
];
