[Service]
NoNewPrivileges=true
ProtectSystem=strict
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectControlGroups=true
ProtectClock=true
ProtectHostname=true
RestrictSUIDSGID=true
RestrictRealtime=true
RestrictNamespaces=true
LockPersonality=true
PrivateTmp=true
PrivateDevices=true
SystemCallArchitectures=native
CapabilityBoundingSet=
AmbientCapabilities=
