[Service]
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/var/lib/nats /var/log/nats
PrivateTmp=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
RestrictRealtime=true
LockPersonality=true
SystemCallArchitectures=native
CapabilityBoundingSet=
