export * from '../../../../platform/dos/workflows/types/workflow-types';
export * from '../../../../platform/dos/workflows/engine/workflow-crud.service';

export {
  startWorkflowExecution,
  advanceStep,
  completeStep,
  cancelExecution,
  getInstanceStatus,
  evaluateTransitionConditions,
  createApprovalForStep,
  onApprovalResolved,
  getFailurePath,
  emitWorkflowEvent,
  emitWorkflowEvent as emitWorkflowEntityEvent,
  executeNotificationStep,
  executeApiCallNode,
  executeSendEmailNode,
  executeWebhookNode,
  EMPTY_RESOLUTION,
  SLA_DEFAULTS,
  TASK_TYPE_TO_PERMISSION_ACTION,
  TASK_PRIORITY_TO_MIN_AUTHORITY,
  tableExists,
  columnExists,
  getTaskTypePermissionAction,
  getEntityModule,
  getEntityTable,
  getFallbackDomain,
  resolveByRoleHint,
  resolveByRecordOwnership,
  resolveByEnterpriseAuthz,
  resolveByDynamicRACI,
  resolveByFallbackMap,
  lookupSLA,
  createProcessTask,
  completeProcessTask,
  notifyRACIInformed,
  logRoutingDecision,
} from '../../../../platform/dos/workflows';
export type {
  EngineStep,
  EngineTransition,
  EngineCondition,
  InstanceStepRecord,
  StartResult,
  AdvanceResult,
  WorkflowEventType,
  WorkflowEventPayload,
  WorkflowEntityType,
  WorkflowAction,
  ProcessTaskType,
  ProcessTaskInput,
  ProcessTask,
  RoutingResolution,
} from '../../../../platform/dos/workflows';

export { getWorkflowAnalytics } from '../../../../platform/dos/workflows/actions/workflow-actions.service';
