/**
 * Default entity routing maps (code-defined).
 * Loaded at startup; tenant `entity_routing_config` rows merge on top via entity-routing-bootstrap.
 */

export const DEFAULT_ENTITY_MODULES: Record<string, string> = {
  risk: 'risk',
  control: 'compliance',
  policy: 'policy',
  evidence: 'evidence',
  vendor: 'vendor',
  incident: 'incident',
  finding: 'audit',
  assessment: 'audit',
  compliance_gap: 'compliance',
  remediation_task: 'remediation',
  remediation: 'remediation',
  governance_action: 'governance',
  committee: 'governance',
  procedure: 'governance',
  mandate: 'governance',
  enforcement_violation: 'governance',
  exception: 'exception',
  change: 'governance',
  privacy: 'governance',
  user: 'admin',
  report: 'analytics',
  bcm: 'bcp',
  bcp: 'bcp',
  asset: 'asset',
  action: 'task',
  governance: 'governance',
  delegation: 'governance',
  obligation: 'governance',
  responsibility: 'governance',
  charter: 'governance',
  objective: 'governance',
  board_pack: 'governance',
  governance_auto_fire: 'governance',
  vendor_risk: 'risk',
  vendor_finding: 'audit',
  vendor_evidence: 'evidence',
  vendor_compliance_gap: 'compliance',
  training_assignment: 'training',
  training_campaign: 'training',
  training_content: 'training',
  workflow: 'workflow',
  workflow_task: 'workflow',
  workflow_approval: 'workflow',
};

export const DEFAULT_ENTITY_TABLES: Record<
  string,
  { table: string; pk: string; ownerCol: string; reviewerCol?: string; approverCol?: string; orgUnitCol?: string }
> = {
  risk: { table: 'risks', pk: 'risk_id', ownerCol: 'owner_user_id', reviewerCol: 'reviewer_user_id', approverCol: 'approver_user_id', orgUnitCol: 'org_unit_id' },
  policy: { table: 'policies', pk: 'policy_id', ownerCol: 'author_user_id', reviewerCol: 'reviewer_user_id', approverCol: 'approver_user_id', orgUnitCol: 'org_unit_id' },
  control: { table: 'controls', pk: 'control_id', ownerCol: 'owner_user_id', reviewerCol: 'reviewer_user_id', approverCol: 'approver_user_id', orgUnitCol: 'org_unit_id' },
  evidence: { table: 'evidence', pk: 'evidence_id', ownerCol: 'owner_user_id', reviewerCol: 'reviewer_user_id', orgUnitCol: 'org_unit_id' },
  incident: { table: 'incidents', pk: 'incident_id', ownerCol: 'owner_user_id', reviewerCol: 'reviewer_user_id', approverCol: 'approver_user_id', orgUnitCol: 'org_unit_id' },
  vendor: { table: 'vendors', pk: 'vendor_id', ownerCol: 'owner_user_id', reviewerCol: 'reviewer_user_id', approverCol: 'approver_user_id', orgUnitCol: 'org_unit_id' },
  finding: { table: 'findings', pk: 'finding_id', ownerCol: 'auditee_owner_user_id', reviewerCol: 'auditor_user_id', approverCol: 'approver_user_id', orgUnitCol: 'org_unit_id' },
  workflow: { table: 'workflows', pk: 'workflow_id', ownerCol: 'created_by' },
};

export const DEFAULT_FALLBACK_DOMAINS: Record<string, { scopeType: string; scopeId: string; fallbackTeamCode: string }> = {
  risk: { scopeType: 'process', scopeId: 'risk_management', fallbackTeamCode: 'ERM' },
  control: { scopeType: 'process', scopeId: 'compliance_monitoring', fallbackTeamCode: 'CYBER_GOV' },
  policy: { scopeType: 'process', scopeId: 'compliance_monitoring', fallbackTeamCode: 'QUALITY' },
  evidence: { scopeType: 'process', scopeId: 'audit_assurance', fallbackTeamCode: 'AUDIT' },
  vendor: { scopeType: 'process', scopeId: 'vendor_risk_assessment', fallbackTeamCode: 'VENDOR_RISK' },
  incident: { scopeType: 'process', scopeId: 'incident_response', fallbackTeamCode: 'SOC_OPS' },
  compliance_gap: { scopeType: 'process', scopeId: 'compliance_monitoring', fallbackTeamCode: 'CYBER_GOV' },
  finding: { scopeType: 'process', scopeId: 'audit_assurance', fallbackTeamCode: 'AUDIT' },
  remediation_task: { scopeType: 'process', scopeId: 'risk_management', fallbackTeamCode: 'ERM' },
  remediation: { scopeType: 'process', scopeId: 'risk_management', fallbackTeamCode: 'ERM' },
  assessment: { scopeType: 'process', scopeId: 'audit_assurance', fallbackTeamCode: 'AUDIT' },
  user: { scopeType: 'process', scopeId: 'data_protection', fallbackTeamCode: 'IAM_GOV' },
  report: { scopeType: 'process', scopeId: 'audit_assurance', fallbackTeamCode: 'EXEC_STRATEGY' },
  bcm: { scopeType: 'process', scopeId: 'bcm_disaster_recovery', fallbackTeamCode: 'BCM_DR' },
  bcp: { scopeType: 'process', scopeId: 'bcm_disaster_recovery', fallbackTeamCode: 'BCM_DR' },
  change: { scopeType: 'process', scopeId: 'change_management', fallbackTeamCode: 'SVC_OPS' },
  privacy: { scopeType: 'process', scopeId: 'data_protection', fallbackTeamCode: 'PRIVACY' },
  exception: { scopeType: 'process', scopeId: 'compliance_monitoring', fallbackTeamCode: 'CYBER_GOV' },
  governance_action: { scopeType: 'process', scopeId: 'governance_oversight', fallbackTeamCode: 'CYBER_GOV' },
  committee: { scopeType: 'process', scopeId: 'governance_oversight', fallbackTeamCode: 'EXEC_STRATEGY' },
  procedure: { scopeType: 'process', scopeId: 'compliance_monitoring', fallbackTeamCode: 'QUALITY' },
  mandate: { scopeType: 'process', scopeId: 'governance_oversight', fallbackTeamCode: 'EXEC_STRATEGY' },
  enforcement_violation: { scopeType: 'process', scopeId: 'compliance_monitoring', fallbackTeamCode: 'CYBER_GOV' },
  governance: { scopeType: 'process', scopeId: 'governance_oversight', fallbackTeamCode: 'EXEC_STRATEGY' },
  asset: { scopeType: 'process', scopeId: 'data_protection', fallbackTeamCode: 'IAM_GOV' },
  action: { scopeType: 'process', scopeId: 'task_management', fallbackTeamCode: 'SVC_OPS' },
  delegation: { scopeType: 'process', scopeId: 'governance_oversight', fallbackTeamCode: 'EXEC_STRATEGY' },
  obligation: { scopeType: 'process', scopeId: 'compliance_monitoring', fallbackTeamCode: 'CYBER_GOV' },
  responsibility: { scopeType: 'process', scopeId: 'governance_oversight', fallbackTeamCode: 'EXEC_STRATEGY' },
  charter: { scopeType: 'process', scopeId: 'governance_oversight', fallbackTeamCode: 'EXEC_STRATEGY' },
  objective: { scopeType: 'process', scopeId: 'governance_oversight', fallbackTeamCode: 'EXEC_STRATEGY' },
  board_pack: { scopeType: 'process', scopeId: 'governance_oversight', fallbackTeamCode: 'EXEC_STRATEGY' },
  governance_auto_fire: { scopeType: 'process', scopeId: 'governance_oversight', fallbackTeamCode: 'CYBER_GOV' },
  vendor_risk: { scopeType: 'process', scopeId: 'risk_management', fallbackTeamCode: 'ERM' },
  vendor_finding: { scopeType: 'process', scopeId: 'audit_assurance', fallbackTeamCode: 'AUDIT' },
  vendor_evidence: { scopeType: 'process', scopeId: 'audit_assurance', fallbackTeamCode: 'AUDIT' },
  vendor_compliance_gap: { scopeType: 'process', scopeId: 'compliance_monitoring', fallbackTeamCode: 'CYBER_GOV' },
  training_assignment: { scopeType: 'process', scopeId: 'training_awareness', fallbackTeamCode: 'CYBER_GOV' },
  training_campaign: { scopeType: 'process', scopeId: 'training_awareness', fallbackTeamCode: 'CYBER_GOV' },
  training_content: { scopeType: 'process', scopeId: 'training_awareness', fallbackTeamCode: 'CYBER_GOV' },
  workflow: { scopeType: 'workflow', scopeId: 'workflow_automation', fallbackTeamCode: 'QUALITY' },
  workflow_task: { scopeType: 'workflow', scopeId: 'workflow_automation', fallbackTeamCode: 'QUALITY' },
  workflow_approval: { scopeType: 'workflow', scopeId: 'workflow_automation', fallbackTeamCode: 'EXEC_STRATEGY' },
};
