module.exports = {
  apps: [
    {
      name: 'dos-platform',
      script: 'backend/dist/server.js',
      instances: 'max',
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3010,
        PLATFORM_NAME: 'dos-platform',
        PLATFORM_VERSION: '1.5.0',
        PLATFORM_DOMAIN: 'dogan-ai.com',
        DEPLOYMENT_MODE: 'standalone',
      },
      env_staging: {
        NODE_ENV: 'staging',
        PORT: 3050,
        PLATFORM_NAME: 'dos-platform',
        PLATFORM_VERSION: '1.5.0',
        PLATFORM_DOMAIN: 'staging.dogan-ai.com',
        DEPLOYMENT_MODE: 'standalone',
      },
      error_file: './logs/dos-platform-error.log',
      out_file: './logs/dos-platform-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 10000,
      listen_timeout: 30000,
      shutdown_with_message: true,
      wait_ready: false,
    },
  ],
};
