-- Migration 017: Framework Alias Bootstrap (safe early dependency)
BEGIN;

CREATE TABLE IF NOT EXISTS public.lookup_frameworks (
  framework_code VARCHAR(50) PRIMARY KEY,
  framework_name VARCHAR(255) NOT NULL,
  framework_acronym VARCHAR(50),
  regulatory_body VARCHAR(255),
  jurisdiction VARCHAR(100),
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.lookup_frameworks (
  framework_code,
  framework_name,
  framework_acronym,
  regulatory_body,
  jurisdiction,
  is_active,
  sort_order
)
SELECT
  c.framework_code,
  'Framework ' || upper(replace(c.framework_code, '_', ' ')) AS framework_name,
  upper(c.framework_code) AS framework_acronym,
  'N/A' AS regulatory_body,
  'GLOBAL' AS jurisdiction,
  true AS is_active,
  999 AS sort_order
FROM (
VALUES
  ('aus_asic_rg271'),
  ('aus_cps234'),
  ('aus_essential8'),
  ('aus_ism'),
  ('aus_privacy_act'),
  ('bhr_cbb_cirm'),
  ('bhr_ncea_csf'),
  ('bhr_pdpl'),
  ('cma_cyber'),
  ('cst_crf'),
  ('deu_bsig'),
  ('egy_cbe_cirm'),
  ('egy_fra_gov'),
  ('egy_nccsi_csf'),
  ('egy_pdpl'),
  ('eu_ai_act'),
  ('eu_dora'),
  ('eu_nis2'),
  ('gbr_cyberessentials'),
  ('gbr_fca_sysc'),
  ('gbr_ukgdpr'),
  ('gdpr'),
  ('kwt_cbk_cirm'),
  ('kwt_citra_csf'),
  ('kwt_dpl'),
  ('meim_og'),
  ('moh_his'),
  ('nca_ccc'),
  ('nca_cscc'),
  ('nca_dcc'),
  ('nca_ecc'),
  ('nca_otcc'),
  ('omn_cbo_cirm'),
  ('omn_ita_egov'),
  ('omn_pdpl'),
  ('pdpl'),
  ('qat_nia'),
  ('qat_pdpl'),
  ('qat_qcb_cirm'),
  ('qat_qfcra_dp'),
  ('sama_csf'),
  ('sama_fintech'),
  ('saso_product'),
  ('sdaia_aie'),
  ('sfda_mds'),
  ('tur_bddk_cirm'),
  ('tur_btk_csf'),
  ('tur_kvkk'),
  ('tur_spk_gov'),
  ('uae_adgm_dpr'),
  ('uae_cbuae_cirm'),
  ('uae_difc_dpl'),
  ('uae_fpdl'),
  ('uae_nesa_ias'),
  ('uae_tdra_css'),
  ('usa_ccpa'),
  ('usa_cmmc'),
  ('usa_fedramp'),
  ('usa_ffiec'),
  ('usa_glba'),
  ('usa_hipaa'),
  ('usa_nist_csf2'),
  ('usa_nist_sp800_53'),
  ('usa_sec_cyber'),
  ('usa_sox'),
  ('zatca_einv')
) AS c(framework_code)
ON CONFLICT (framework_code) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.framework_alias (
  alias_code     VARCHAR(80) PRIMARY KEY,
  framework_code VARCHAR(50) NOT NULL REFERENCES public.lookup_frameworks(framework_code),
  source         TEXT DEFAULT 'migration_017_bootstrap',
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_framework_alias_fwcode
  ON public.framework_alias(framework_code);

INSERT INTO public.framework_alias (alias_code, framework_code) VALUES
  ('INST-KSA-SAMA-CSF', 'sama_csf'),
  ('INST-KSA-NCA-ECC', 'nca_ecc'),
  ('INST-KSA-NCA-CCC', 'nca_ccc'),
  ('INST-KSA-NCA-CSCC', 'nca_cscc'),
  ('INST-KSA-NCA-DCC', 'nca_dcc'),
  ('INST-KSA-NCA-OTCC', 'nca_otcc'),
  ('INST-KSA-SDAIA-PDPL', 'pdpl'),
  ('INST-KSA-CMA-CYBER', 'cma_cyber'),
  ('INST-KSA-CST-CRF', 'cst_crf'),
  ('INST-KSA-ZATCA-EINV', 'zatca_einv'),
  ('INST-KSA-SAMA-FINTECH', 'sama_fintech'),
  ('INST-KSA-MEIM-OG', 'meim_og'),
  ('INST-KSA-MOH-HIS', 'moh_his'),
  ('INST-KSA-SASO-PRODUCT', 'saso_product'),
  ('INST-KSA-SDAIA-AIE', 'sdaia_aie'),
  ('INST-KSA-SFDA-MDS', 'sfda_mds'),
  ('INST-UAE-NESA-IAS', 'uae_nesa_ias'),
  ('INST-UAE-CBUAE-CIRM', 'uae_cbuae_cirm'),
  ('INST-UAE-FPDL', 'uae_fpdl'),
  ('INST-UAE-TDRA-CSS', 'uae_tdra_css'),
  ('INST-UAE-ADGM-DPR', 'uae_adgm_dpr'),
  ('INST-UAE-DIFC-DPL', 'uae_difc_dpl'),
  ('INST-BHR-CBB-CIRM', 'bhr_cbb_cirm'),
  ('INST-BHR-NCEA-CSF', 'bhr_ncea_csf'),
  ('INST-BHR-PDPL', 'bhr_pdpl'),
  ('INST-KWT-CBK-CIRM', 'kwt_cbk_cirm'),
  ('INST-KWT-CITRA-CSF', 'kwt_citra_csf'),
  ('INST-KWT-DPL', 'kwt_dpl'),
  ('INST-OMN-CBO-CIRM', 'omn_cbo_cirm'),
  ('INST-OMN-ITA-EGOV', 'omn_ita_egov'),
  ('INST-OMN-PDPL', 'omn_pdpl'),
  ('INST-QAT-QCB-CIRM', 'qat_qcb_cirm'),
  ('INST-QAT-NIA', 'qat_nia'),
  ('INST-QAT-PDPL', 'qat_pdpl'),
  ('INST-QAT-QFCRA-DP', 'qat_qfcra_dp'),
  ('INST-EGY-CBE-CIRM', 'egy_cbe_cirm'),
  ('INST-EGY-NCCSI-CSF', 'egy_nccsi_csf'),
  ('INST-EGY-PDPL', 'egy_pdpl'),
  ('INST-EGY-FRA-GOV', 'egy_fra_gov'),
  ('INST-TUR-BDDK-CIRM', 'tur_bddk_cirm'),
  ('INST-TUR-BTK-CSF', 'tur_btk_csf'),
  ('INST-TUR-KVKK', 'tur_kvkk'),
  ('INST-TUR-SPK-GOV', 'tur_spk_gov'),
  ('INST-EU-GDPR', 'gdpr'),
  ('INST-EU-NIS2', 'eu_nis2'),
  ('INST-EU-DORA', 'eu_dora'),
  ('INST-EU-AI-ACT', 'eu_ai_act'),
  ('INST-GBR-FCA-SYSC', 'gbr_fca_sysc'),
  ('INST-GBR-UKGDPR', 'gbr_ukgdpr'),
  ('INST-GBR-CYBERESSENTIALS', 'gbr_cyberessentials'),
  ('INST-DEU-BSIG', 'deu_bsig'),
  ('INST-USA-HIPAA', 'usa_hipaa'),
  ('INST-USA-SOX', 'usa_sox'),
  ('INST-USA-GLBA', 'usa_glba'),
  ('INST-USA-CCPA', 'usa_ccpa'),
  ('INST-USA-FEDRAMP', 'usa_fedramp'),
  ('INST-USA-CMMC', 'usa_cmmc'),
  ('INST-USA-FFIEC', 'usa_ffiec'),
  ('INST-USA-NIST-CSF2', 'usa_nist_csf2'),
  ('INST-USA-NIST-SP800-53', 'usa_nist_sp800_53'),
  ('INST-USA-SEC-CYBER', 'usa_sec_cyber'),
  ('INST-AUS-CPS234', 'aus_cps234'),
  ('INST-AUS-ESSENTIAL8', 'aus_essential8'),
  ('INST-AUS-ISM', 'aus_ism'),
  ('INST-AUS-PRIVACY-ACT', 'aus_privacy_act'),
  ('INST-AUS-ASIC-RG271', 'aus_asic_rg271')
ON CONFLICT (alias_code) DO NOTHING;

COMMIT;
